# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM nginx:stable-alpine@sha256:4f1f676077c300e5e863bb2458bb3dc6d219a42d91ca0e662a20405468e86f6d
