# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM nginx:stable-alpine@sha256:f67b91c71f9228c7d57ac9a566ae7871e1c674a0b52f09d7510f141220d6518a
