# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM nginx:stable-alpine@sha256:36a205371b630f0e4dea1aebe80952979405fcfc09be1c5f8407d061f4e97651
